[build]
  base = ""
  publish = "build"
  command = "npm run build"
  functions = ".netlify/functions"


[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
